### PR TITLE
Remove mckinsey

### PR DESCRIPTION
**Pull request by maxrothman**
We weren't using it anyways, and it was putting extra materials in
pipelines that didn't need them

### CODE REVIEW

**Comment by feanil** [comment]
Instead of doing this, why not start using these pipelines and give solutions the ability to deploy their own code instead of always asking us?

**Comment by maxrothman** [comment]
My original goal was to remove the unnecessary materials from the pipelines on the edx/edge deployments. If there's a better way of doing that, I'm all ears.

**Comment by feanil** [comment]
It seems like the actual bug is that materials are shared between the
different deployments of edxapp.  That seems like the right bug to fix, by
making it possible to provide different materials to those pipelines than
to the mckinsey one.

**Comment by maxrothman** [comment]
Do you have any sense of how the scope of that change would differ from this one?

**Comment by macdiesel** [comment]
The pre-release/stage pipelines are upstream materials for the production deployments the edx and edge cluster and why McKA was included as part of these materials. 

If we want to fix the real defect here the solution is service discovery/configuration, then these secure and internal repositories no longer need to be part of the build.

**Comment by feanil** [comment]
It looks to me like the problem here is that the 'prod-stage-edxapp.yml' config is shared between McKinsey, edx, and edge.  Why not just make a separate one for McKinsey?

**Comment by macdiesel** [comment]
I'm not opposed to a set of pipelines to deploy the McKA environment.

**Comment by maxrothman** [comment]
Sounds like everyone's 👎 on this change so I'm going to close it, but don't let that stop the discussion.

**Pull request closed without merging**
