### PR TITLE
Added support for automatically deploying AMIs

### PR DESCRIPTION
**Pull request by clintonb**
ECOM-5134

### CODE REVIEW

**Comment by clintonb** [comment]
@edx/pipeline-team please review/merge

**Comment by clintonb** [comment]
@rluicioni FYI

**Comment by rlucioni** [comment]
I'm really excited for this change! (And also to be getting my first look at gomatic.) 👍

**Comment by macdiesel** [comment]
@clintonb Please use the config here. Not every pipeline will want to autodeploy. It is preferable that you use the booleans to let the calling pipelines decide if they want to auto-run and auto-deploy.

Passing them in as as part of the config is sub-optimal. How about moving these items to the method signature?

**Comment by clintonb** [comment]
@macdiesel I chose config due to the fact that, for example, we might want to automatically deploy to stage but not loadtest or production. Are you recommending pulling from configuration in the pipeline (since we only have one pipeline file per play)?

**Comment by macdiesel** [comment]
I'll take this. 👍

**Pull request merged**
