### PR TITLE
Mistake where first stage of rollback pipelines did not contain manua…

### PR DESCRIPTION
**Pull request by Dillon-Dumesnil**
…l approval. Also moved all of the deployment code to be together for the deploy to stage stage. Realized it was split up.
@edx/pipeline-team please review

### CODE REVIEW

**Comment by doctoryes** [comment]
LGTM - I'll let @macdiesel thumb it, though....

**Comment by Dillon-Dumesnil** [comment]
Actually am making a few other changes that I still need to manually verify. Please do not merge yet. Adding in functionality to deploy any name and not just tags. Will add in a new commit so changes are obvious.

**Comment by Dillon-Dumesnil** [comment]
@macdiesel I have verified this PRs changes. Please review when you have the chance. @doctoryes If you could take a look at the second commit, that would be nice too. Thanks!

**Comment by macdiesel** [comment]
👍

**Pull request merged**
