### PR TITLE
remove not from auto_run and auto_deploy_ami flags

### PR DESCRIPTION
**Pull request by macdiesel**
@clintonb I do not believe that these not statements should be part of these flags.

### CODE REVIEW

**Comment by clintonb** [comment]
@macdiesel if we want to auto-deploy, `manual_approval` should be `False`.

**Comment by macdiesel** [comment]
I agree, so pass in your override via a config file in gomatic-secure? All those variables in those files end up in the config dict.

**Comment by macdiesel** [comment]
I think this is where we got tripped up on this last week.

**Comment by macdiesel** [comment]
I'm going to change these verbs. Too confusing.

**Pull request closed without merging**
