### PR TITLE
Support for internal configuration repos

### PR DESCRIPTION
**Pull request by jibsheet**
@macdiesel
@edx/devops

### CODE REVIEW

**Comment by jibsheet** [comment]
There are 3 pipelines, all prefixed with kevin- if you want to see the sample generated pipelines, and run against a PR where I enable the config checking again.

**Comment by jibsheet** [comment]
Notes that we should also merge
https://github.com/edx-ops/edge-secure/pull/304
https://github.com/edx-ops/edx-secure/pull/1040
https://github.com/edx-ops/gomatic-secure/pull/64

**Comment by macdiesel** [comment]
@jibsheet I'm going to thumb this with the assumption that you created a test pipeline for edxapp and an IDA and did a deployment to stage or load test and everything worked as expected.

👍

**Comment by jibsheet** [comment]
@macdiesel Yep - I stopped short of deploy, because the change only impacts run_play, so I let the run_play run on analytics, ecommerce and edxapp and confirmed an AMI was built.

**Comment by macdiesel** [comment]
@jibsheet everything looks good. When do you want to land the mothership?

**Comment by jibsheet** [comment]
Seems like we have another hotfix in flight, so tomorrow after all hands before the edx platform release starts I think.
I'm the release buddy so I'll sync it around Chris Lee.

**Pull request merged**
