### PR TITLE
Change the branch for microsites Jenkins job.

### PR DESCRIPTION
**Pull request by raeeschachar**

### CODE REVIEW

**Comment by raeeschachar** [comment]
@edx/pipeline-team 
Another part of https://openedx.atlassian.net/browse/TE-2097. Please review. 
As the whitelabel tests are now ported, we won't require a release pipeline run on kashif/whitelabel rather on master.

**Comment by doctoryes** [comment]
@raeeschachar I'm curious - in which repo does this switch to using the `master` branch?

**Comment by raeeschachar** [comment]
@doctoryes 
I am a new to this, should have added more details.
https://screencast.com/t/W6EXqAIB2
Seems like on Jenkins it is using the correct github repo but expecting a CI Branch that I changed to master instead of kashif/whitelabel (a branch in https://github.com/edx/edx-e2e-tests repo). Hope that makes sense.

**Comment by doctoryes** [comment]
@raeeschachar Ah yes - I should have known that!

**Comment by raeeschachar** [comment]
@edx/pipeline-team 
Merge displays: Only those with write access to this repository can merge pull requests.
Can anyone merge this PR please?

**Comment by doctoryes** [comment]
@estute I merged - but can you please get @raeeschachar merge privileges?

**Pull request merged**
