### PR TITLE
Deploy notes to prod-edge in addition to the rest.

### PR DESCRIPTION
**Pull request by pwnage101**

### CODE REVIEW

**Comment by yro** [comment]
@pwnage101 Is this it? I actually edited away from this. Nice work.

**Comment by pwnage101** [comment]
Not 100% sure, but this is the hint i got from kevin.  I guess we'll find out!  You'll see that this is almost line-for-line the same as the cd_insights.py file.

**Comment by yro** [comment]
@pwnage101 So much heartache could have been saved. Thanks for taking this on.

**Comment by pwnage101** [comment]
@jibsheet thanks, can you also merge this since I don't have authorization?

**Comment by jibsheet** [comment]
@pwnage101 I think it's still going to fail loading that yml file, but at least it's merged

**Pull request merged**
